title: Refactoring Journey
remote_theme: pmarsceill/just-the-docs
color_scheme: dark
footer_content: "Journey proposed by <a href=\"https://www.linkedin.com/in/yoanthirion/\">Yoan Thirion</a> #sharingiscaring"
exclude:
  - README.md